# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' Save a dataset as CSV
#' It saves a dataset as a csv file with a defined path
#' 
#' @param data Dataframe. The dataset to 
#' 
#' @return
#' 
#' @export
#' @examples
#' save_as_csv()
save_as_csv <- function(){
    
}
