# WARNING - Generated by {fusen} from /dev/flat_study_squirrels.Rmd: do not edit by hand

#' study_activity
#' 
#' Asses the available data and the variable with the primary fur colors of the squirrels. Then, generates a table and a graph.
#' 
#' @return A list with the outputs
#' 
#' @importFrom ggplot2 ggplot aes geom_col labs scale_fill_manual
#' @importFrom dplyr %>% filter
#' 
#' @param df_squirrels_act Dataframe. Sample data of squirrels
#' @param col_primary_fur_color Character String. The column with the fur colors
#' 
#' @export
#'
#' @examples
#' data(DATASET)
#' study_activity(df_squirrels_act = DATASET, 
#'                col_primary_fur_color = "Gray")
study_activity <- function(df_squirrels_act, col_primary_fur_color) {
  
  stopifnot(is.data.frame(df_squirrels_act))
  stopifnot(is.character(col_primary_fur_color))
  
  table <- df_squirrels_act %>% 
    filter(col_primary_fur_color == primary_fur_color)
    
  graph <- table %>% 
    ggplot() +
    aes(x = activity, y = counts, fill = age) +
    geom_col() +
    labs(x = "Type of activity",
         y = "Number of observations",
         title = glue("Type of activity by age for {tolower(col_primary_fur_color)} squirrels")) +
    scale_fill_manual(name = "Age",
                      values = c("#00688B", "#00BFFF"))
  
  return(list(table = table, graph = graph))
}
